### ISSUE TITLE
TypeError: Cannot read property 'access_token' of null

### ISSUE THREAD

**Issue by kevin-leptons** [kevin-leptons/trop_diary_nodejs#1]
```bash
TypeError: Cannot read property 'access_token' of null
    at HttpMiddleware.set_token (/mnt/store/package/trop_diary_cli/node_modules/@trop/diary_nodejs/lib/http_middleware.js:12:45)
    at AuthService.set_token (/mnt/store/package/trop_diary_cli/node_modules/@trop/diary_nodejs/lib/auth_service.js:12:20)
    at Object.load (/mnt/store/package/trop_diary_cli/lib/auth.js:64:12)
    at cli_account_list (/mnt/store/package/trop_diary_cli/lib/service.js:29:30)
    at Object.handler (/mnt/store/package/trop_diary_cli/bin/cli.js:61:9)
    at Object.runCommand (/mnt/store/package/trop_diary_cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/mnt/store/package/trop_diary_cli/node_modules/yargs/yargs.js:1063:30)
    at Object.get [as argv] (/mnt/store/package/trop_diary_cli/node_modules/yargs/yargs.js:1004:21)
    at Object.<anonymous> (/mnt/store/package/trop_diary_cli/bin/cli.js:56:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by kevin-leptons** [comment]
Done
