### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by kevin-leptons** [kevin-leptons/trop_diary_nodejs#2]
TypeError: Cannot read property 'status' of undefined
    at HttpService._request (/home/kevin/package/trop_diary_cli/node_modules/@trop/diary_nodejs/lib/http_service.js:50:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kevin-leptons** [comment]
Done

**Comment by kevin-leptons** [comment]
```text
TypeError: Cannot read property 'status' of undefined
    at HttpService._request (/home/kevin/package/trop_diary_cli/node_modules/@trop/diary_nodejs/lib/http_service.js:48:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Oops!, Unexpected Error Just Happend
```

**Comment by kevin-leptons** [comment]
Error cause by API endpoint can be reach

**Comment by kevin-leptons** [comment]
Done: b6b8bf63433ccde574b1f7239ce635c6fbc7dd0d
